database:
  host: "localhost"
  port: 3306
  name: "database_name"
  user: "database_user"
  password: "password"

settings:
  Join-messages: true
  leave-messages: true
  death-message: true
  final-message: true
  life-number: 3
