database:
  host: "localhost"
  port: 3306
  name: "nome_database"
  user: "nome_utente"
  password: "password"

settings:
  Join-messages: true
  leave-messages: true
  death-message: true
  final-message: true
  life-number: 3
